package li.naska.bgg.resource.v5.model;

public enum SearchContext {
  boardgame,
  boardgameaccessory,
  boardgameartist,
  boardgamedesigner,
  boardgamefamily,
  boardgamehonor,
  boardgamepublisher,
  rpg,
  rpgartist,
  rpgdesigner,
  rpgissue,
  rpgissuearticle,
  rpgitem,
  rpgperiodical,
  rpgproducer,
  rpgpublisher,
  rpgseries,
  rpgsetting,
  rpgsystem,
  rpgunified,
  videogame,
  videogamecharacter,
  videogamedeveloper,
  videogamefranchise,
  videogamegenre,
  videogamehardware,
  videogameplatform,
  videogameseries,
  videogametheme,
  videogameunified
}
