name: build native

on:
  push:
    branches: [ 'master', 'feature/**' ]
    tags: [ 'v*.*.*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: bgg-api-native
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE: ${{ github.repository }}-native
  DOCKER_FILE: Dockerfile.native
  DOCKER_COMPOSE_FILE: docker-compose.native.yml

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write

    steps:
      # build

      - name: Checkout project
        uses: actions/checkout@v6

      - name: Set up JDK and Maven
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm
          java-version: 25
          cache: maven

      - name: Build with Maven
        run: |
          mvn --batch-mode native:compile -Pnative

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          load: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:master

      - name: Test Docker image
        env:
          BGG_APPLICATION_TOKEN: dummy
        run: |
          trap 'docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} down --remove-orphans' EXIT
          docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d --wait --wait-timeout 60
          docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} ps --format json | grep -q '"Health":"healthy"'

      # publish

      - name: Login to Docker registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        if: github.ref == 'refs/heads/master'
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}

      - name: Publish Docker image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    environment:
      name: native-staging
      url: ${{ steps.deploy-to-azure-webapp.outputs.webapp-url }}/bgg-api/actuator/health

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-azure-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}-staging
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_NATIVE_STAGING }}
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:master
