name: build native executable

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

env:
  TEST_TAG: ${{ secrets.DOCKER_HUB_USERNAME }}/bgg-api-native:test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up GraalVM version
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.0.0.2'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract maven project version
        run: |
          echo "MAVEN_PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build native app with Maven
        run: |
          mvn clean package -Pnative -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test image
        run: |
          DOCKER_PID=$(docker run -d -p 8088:8088 --rm ${{ env.TEST_TAG }} 2>/dev/null)
          curl http://localhost:8088/bgg-api/v3/api-docs/v3
          docker stop $DOCKER_PID

      - name: Set tags for master branch
        run: |
          echo "DOCKER_HUB_TAGS=${{ secrets.DOCKER_HUB_USERNAME }}/bgg-api-native:latest,${{ secrets.DOCKER_HUB_USERNAME }}/bgg-api-native:${{ env.MAVEN_PROJECT_VERSION }}" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/master'

      - name: Set tags for develop branch
        run: |
          echo "DOCKER_HUB_TAGS=${{ secrets.DOCKER_HUB_USERNAME }}/bgg-api-native:develop" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/develop'

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_TAGS }}
